//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrowlend
    {
        public borrowlend()
        {
            this.borrowlendstocks = new HashSet<borrowlendstock>();
        }
    
        public int borrowLendId { get; set; }
        public bool Status { get; set; }
        public Nullable<int> orderIdAgaintBorrowed { get; set; }
    
        public virtual ICollection<borrowlendstock> borrowlendstocks { get; set; }
    }
}
