//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrowlendstock
    {
        public int borrowLendStockId { get; set; }
        public int stockId { get; set; }
        public int borrowLendId { get; set; }
        public Nullable<int> quantityBorrowed { get; set; }
        public Nullable<double> amount { get; set; }
    
        public virtual borrowlend borrowlend { get; set; }
        public virtual stock stock { get; set; }
    }
}
