//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class designation
    {
        public designation()
        {
            this.designation11 = new HashSet<designation>();
            this.employees = new HashSet<employee>();
        }
    
        public int designationId { get; set; }
        public string designation1 { get; set; }
        public Nullable<int> level { get; set; }
        public int parentDesignationId { get; set; }
    
        public virtual ICollection<designation> designation11 { get; set; }
        public virtual designation designation2 { get; set; }
        public virtual ICollection<employee> employees { get; set; }
    }
}
