//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.orderhistories = new HashSet<orderhistory>();
            this.orderdetails = new HashSet<orderdetail>();
            this.productsorderds = new HashSet<productsorderd>();
        }
    
        public int orderId { get; set; }
        public System.DateTime orderDate { get; set; }
        public int empId { get; set; }
        public int orderStatusId { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual orderstatu orderstatu { get; set; }
        public virtual ICollection<orderhistory> orderhistories { get; set; }
        public virtual ICollection<orderdetail> orderdetails { get; set; }
        public virtual ICollection<productsorderd> productsorderds { get; set; }
    }
}
