//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderstatu
    {
        public orderstatu()
        {
            this.orders = new HashSet<order>();
        }
    
        public int orderStatusId { get; set; }
        public string statusName { get; set; }
        public string statusDiscription { get; set; }
    
        public virtual ICollection<order> orders { get; set; }
    }
}
