//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public orderdetail()
        {
            this.stocks = new HashSet<stock>();
        }
    
        public int orderDetailId { get; set; }
        public Nullable<int> quantityRecived { get; set; }
        public Nullable<int> quantityOrderd { get; set; }
        public Nullable<System.DateTime> orderRecivingDate { get; set; }
        public string description { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<double> discountAmount { get; set; }
        public Nullable<double> netValue { get; set; }
        public int productSuppliedId { get; set; }
        public int orderId { get; set; }
    
        public virtual ICollection<stock> stocks { get; set; }
        public virtual order order { get; set; }
        public virtual productsupplied productsupplied { get; set; }
    }
}
