//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderhistory
    {
        public int orderHistoryId { get; set; }
        public string statusChanged { get; set; }
        public string discription { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string employeeId { get; set; }
        public int orderId { get; set; }
    
        public virtual order order { get; set; }
    }
}
