//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagmentSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pharmacyEntities : DbContext
    {
        public pharmacyEntities()
            : base("name=pharmacyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<authority> authorities { get; set; }
        public DbSet<borrowlend> borrowlends { get; set; }
        public DbSet<borrowlendstock> borrowlendstocks { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<department> departments { get; set; }
        public DbSet<designation> designations { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<employerstock> employerstocks { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<orderdetail> orderdetails { get; set; }
        public DbSet<orderhistory> orderhistories { get; set; }
        public DbSet<orderstatu> orderstatus { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<productdetail> productdetails { get; set; }
        public DbSet<productsupplied> productsupplieds { get; set; }
        public DbSet<sale> sales { get; set; }
        public DbSet<solditem> solditems { get; set; }
        public DbSet<stock> stocks { get; set; }
        public DbSet<stocksale> stocksales { get; set; }
        public DbSet<supplier> suppliers { get; set; }
        public DbSet<user> users { get; set; }
    }
}
