//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productdetail
    {
        public productdetail()
        {
            this.productsupplieds = new HashSet<productsupplied>();
        }
    
        public int productDetailId { get; set; }
        public int productId { get; set; }
        public double productSize { get; set; }
    
        public virtual product product { get; set; }
        public virtual ICollection<productsupplied> productsupplieds { get; set; }
    }
}
