//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsupplied
    {
        public productsupplied()
        {
            this.productsorderds = new HashSet<productsorderd>();
        }
    
        public int productSuppliedId { get; set; }
        public int productDetailId { get; set; }
        public int supplierId { get; set; }
    
        public virtual productdetail productdetail { get; set; }
        public virtual ICollection<productsorderd> productsorderds { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
